AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: AWS Service Report Generator - Automated Excel reporting from infrastructure data

Globals:
  Function:
    Timeout: 300
    MemorySize: 512
    Runtime: nodejs20.x
    Architectures:
      - arm64
    Tags:
      Environment: prod
      ManagedBy: sam
      Owner: John Xanthopoulos
      Project: aws-services
      Service: aws-service-report-generator
      GithubRepo: github.com/jxman/aws-services-reporter

Parameters:
  SourceBucketName:
    Type: String
    Default: aws-data-fetcher-output
    Description: S3 bucket containing source data

  NotificationEmail:
    Type: String
    Default: jxman@hotmail.com
    Description: Email address for report notifications
    AllowedPattern: ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$

  DistributionBucketName:
    Type: String
    Default: ''
    Description: (Optional) S3 bucket for public distribution (e.g., www.aws-services.synepho.com). Leave empty to disable distribution.

  DistributionKeyPath:
    Type: String
    Default: reports/aws-service-report-latest.xlsx
    Description: S3 key path in distribution bucket for the report

Conditions:
  HasDistributionBucket: !Not [!Equals [!Ref DistributionBucketName, '']]

Resources:
  # KMS Key for SNS Topic and CloudWatch Logs Encryption
  SNSEncryptionKey:
    Type: AWS::KMS::Key
    Properties:
      Description: KMS key for encrypting SNS topic notifications and CloudWatch Logs
      EnableKeyRotation: true
      Tags:
        - Key: Name
          Value: aws-service-report-encryption-key
        - Key: SubService
          Value: kms-encryption
        - Key: Environment
          Value: prod
        - Key: ManagedBy
          Value: sam
        - Key: Owner
          Value: John Xanthopoulos
        - Key: Project
          Value: aws-services
        - Key: Service
          Value: aws-service-report-generator
        - Key: GithubRepo
          Value: github.com/jxman/aws-services-reporter
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          # Root account administrative access
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: kms:*
            Resource: '*'
          # SNS service access to use the key
          - Sid: Allow SNS to use the key
            Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Action:
              - kms:Decrypt
              - kms:GenerateDataKey
            Resource: '*'
          # CloudWatch Alarms access
          - Sid: Allow CloudWatch Alarms to publish
            Effect: Allow
            Principal:
              Service: cloudwatch.amazonaws.com
            Action:
              - kms:Decrypt
              - kms:GenerateDataKey
            Resource: '*'
          # CloudWatch Logs access
          - Sid: Allow CloudWatch Logs to use the key
            Effect: Allow
            Principal:
              Service: !Sub logs.${AWS::Region}.amazonaws.com
            Action:
              - kms:Decrypt
              - kms:DescribeKey
              - kms:Encrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:CreateGrant
            Resource: '*'
            Condition:
              ArnLike:
                kms:EncryptionContext:aws:logs:arn: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/aws-service-report-generator
          # Allow Lambda execution roles in this account
          - Sid: Allow Lambda execution roles
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action:
              - kms:Decrypt
              - kms:GenerateDataKey
            Resource: '*'
            Condition:
              StringLike:
                aws:PrincipalArn: !Sub arn:aws:iam::${AWS::AccountId}:role/aws-service-report-generator-*

  # KMS Key Alias
  SNSEncryptionKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/aws-service-report-encryption
      TargetKeyId: !Ref SNSEncryptionKey

  # SNS Topic for Notifications
  ReportNotificationsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: aws-service-report-notifications
      DisplayName: AWS Service Report Notifications
      KmsMasterKeyId: !Ref SNSEncryptionKey
      Tags:
        - Key: Name
          Value: aws-service-report-notifications
        - Key: SubService
          Value: sns-notifications
        - Key: Environment
          Value: prod
        - Key: ManagedBy
          Value: sam
        - Key: Owner
          Value: John Xanthopoulos
        - Key: Project
          Value: aws-services
        - Key: Service
          Value: aws-service-report-generator
        - Key: GithubRepo
          Value: github.com/jxman/aws-services-reporter
      Subscription:
        - Endpoint: !Ref NotificationEmail
          Protocol: email

  # Lambda Function
  ReportGeneratorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: aws-service-report-generator
      Description: Generates Excel reports from AWS infrastructure data
      CodeUri: src/
      Handler: index.handler
      Tags:
        Name: aws-service-report-generator
        SubService: report-generator-lambda
      Environment:
        Variables:
          SOURCE_BUCKET: !Ref SourceBucketName
          SOURCE_KEY: aws-data/complete-data.json
          REPORT_BUCKET: !Ref SourceBucketName
          REPORT_PREFIX: reports/
          ARCHIVE_PREFIX: reports/archive/
          LATEST_REPORT_NAME: aws-service-report-latest.xlsx
          ARCHIVE_RETENTION_DAYS: '7'
          SNS_TOPIC_ARN: !Ref ReportNotificationsTopic
          DISTRIBUTION_BUCKET: !Ref DistributionBucketName
          DISTRIBUTION_KEY: !Ref DistributionKeyPath
          NODE_ENV: production
      Policies:
        - Version: '2012-10-17'
          Statement:
            # S3 Read Access (Source Data)
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource: !Sub arn:aws:s3:::${SourceBucketName}/aws-data/*
            # S3 Write/Delete Access (Reports)
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:PutObjectAcl
                - s3:DeleteObject
              Resource: !Sub arn:aws:s3:::${SourceBucketName}/reports/*
            # S3 List Access (Archive Management)
            - Effect: Allow
              Action:
                - s3:ListBucket
              Resource: !Sub arn:aws:s3:::${SourceBucketName}
              Condition:
                StringLike:
                  s3:prefix:
                    - reports/archive/*
            # SNS Publish Access
            - Effect: Allow
              Action:
                - sns:Publish
              Resource: !Ref ReportNotificationsTopic
            # KMS Access (SNS Encryption)
            - Effect: Allow
              Action:
                - kms:Decrypt
                - kms:GenerateDataKey
              Resource: !GetAtt SNSEncryptionKey.Arn
            # CloudWatch Logs (Basic Execution)
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/aws-service-report-generator:*
        # Distribution Bucket Access (Conditional)
        - !If
          - HasDistributionBucket
          - Version: '2012-10-17'
            Statement:
              # S3 Read Access (Copy Source)
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub arn:aws:s3:::${SourceBucketName}/reports/aws-service-report-latest.xlsx
              # S3 Write Access (Distribution Destination)
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                Resource: !Sub arn:aws:s3:::${DistributionBucketName}/${DistributionKeyPath}
          - !Ref AWS::NoValue

  # S3 Event Permission for Lambda
  ReportGeneratorS3Permission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ReportGeneratorFunction
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub arn:aws:s3:::${SourceBucketName}

  # CloudWatch Log Group
  ReportGeneratorLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${ReportGeneratorFunction}
      RetentionInDays: 30
      KmsKeyId: !GetAtt SNSEncryptionKey.Arn
      Tags:
        - Key: Name
          Value: /aws/lambda/aws-service-report-generator
        - Key: SubService
          Value: cloudwatch-logs
        - Key: Environment
          Value: prod
        - Key: ManagedBy
          Value: sam
        - Key: Owner
          Value: John Xanthopoulos
        - Key: Project
          Value: aws-services
        - Key: Service
          Value: aws-service-report-generator
        - Key: GithubRepo
          Value: github.com/jxman/aws-services-reporter

  # CloudWatch Alarms
  ReportGeneratorErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: aws-service-report-generator-errors
      AlarmDescription: Alert when Lambda function encounters errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 86400  # 1 day
      EvaluationPeriods: 1
      Threshold: 0
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref ReportGeneratorFunction
      AlarmActions:
        - !Ref ReportNotificationsTopic
      TreatMissingData: notBreaching
      Tags:
        - Key: Name
          Value: aws-service-report-generator-errors
        - Key: SubService
          Value: alarm-errors
        - Key: Environment
          Value: prod
        - Key: ManagedBy
          Value: sam
        - Key: Owner
          Value: John Xanthopoulos
        - Key: Project
          Value: aws-services
        - Key: Service
          Value: aws-service-report-generator
        - Key: GithubRepo
          Value: github.com/jxman/aws-services-reporter

  ReportGeneratorTimeoutAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: aws-service-report-generator-timeout-warning
      AlarmDescription: Alert when Lambda duration approaches timeout
      MetricName: Duration
      Namespace: AWS/Lambda
      Statistic: Maximum
      Period: 3600  # 1 hour
      EvaluationPeriods: 1
      Threshold: 240000  # 240 seconds (4 minutes)
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref ReportGeneratorFunction
      AlarmActions:
        - !Ref ReportNotificationsTopic
      TreatMissingData: notBreaching
      Tags:
        - Key: Name
          Value: aws-service-report-generator-timeout-warning
        - Key: SubService
          Value: alarm-timeout
        - Key: Environment
          Value: prod
        - Key: ManagedBy
          Value: sam
        - Key: Owner
          Value: John Xanthopoulos
        - Key: Project
          Value: aws-services
        - Key: Service
          Value: aws-service-report-generator
        - Key: GithubRepo
          Value: github.com/jxman/aws-services-reporter

Outputs:
  ReportGeneratorFunctionArn:
    Description: ARN of the report generator Lambda function
    Value: !GetAtt ReportGeneratorFunction.Arn
    Export:
      Name: aws-service-report-generator-arn

  ReportGeneratorFunctionName:
    Description: Name of the report generator Lambda function
    Value: !Ref ReportGeneratorFunction

  ReportNotificationsTopicArn:
    Description: ARN of the SNS topic for notifications
    Value: !Ref ReportNotificationsTopic
    Export:
      Name: aws-service-report-notifications-topic-arn

  SNSEncryptionKeyArn:
    Description: ARN of the KMS key used for SNS topic encryption
    Value: !GetAtt SNSEncryptionKey.Arn
    Export:
      Name: aws-service-report-sns-encryption-key-arn

  SNSEncryptionKeyId:
    Description: ID of the KMS key used for SNS topic encryption
    Value: !Ref SNSEncryptionKey

  LatestReportS3Path:
    Description: S3 path to the latest report
    Value: !Sub s3://${SourceBucketName}/reports/aws-service-report-latest.xlsx

  ArchiveReportsS3Path:
    Description: S3 path to archived reports
    Value: !Sub s3://${SourceBucketName}/reports/archive/

  S3EventConfigurationCommand:
    Description: Command to configure S3 event notification (run after deployment)
    Value: !Sub |
      aws s3api put-bucket-notification-configuration \
        --bucket ${SourceBucketName} \
        --notification-configuration '{
          "LambdaFunctionConfigurations": [{
            "LambdaFunctionArn": "${ReportGeneratorFunction.Arn}",
            "Events": ["s3:ObjectCreated:*"],
            "Filter": {
              "Key": {
                "FilterRules": [
                  {"Name": "prefix", "Value": "aws-data/"},
                  {"Name": "suffix", "Value": "complete-data.json"}
                ]
              }
            }
          }]
        }'
